### ISSUE TITLE
calantha blake dialogue and may o'connell animation

### ISSUE THREAD

**Issue by mechcentric** [henbagle/LE1CommunityPatch#107]
initial conversation with calantha blake in zhu's hope cuts off the part about shepard being "very important" (it is in the subtitles, however). talking to may o'connell after killing thorian and doing her power cell mission makes her kneel down, continue talking, then suddenly appear standing up.

**Comment by S-Carter-of-Mars** [comment]
Playing on PS5, having the same issue with Calantha Blake's dialogue.

**Comment by henbagle** [comment]
I'm going to close this issue as a duplicate, as both the problems stated here have other issues open with more info. The Calantha Blake issue has been fixed and will be in 1.7. The May O'Connell issue is the bane of my existence.

Thanks for your detailed bug reports folks!
