### ISSUE TITLE
Multi Bugs and Issues I Think

### ISSUE THREAD

**Issue by ShredzAlot** [henbagle/LE1CommunityPatch#109]
Normandy: - Navigator Pressly is not close enough to his console. (hands don't reach)
	           
![ScreenShot00002](https://user-images.githubusercontent.com/95461294/144548338-63e53132-33d4-418d-adcb-eb1eed9eb14d.jpg)

- Ashley is also the same way at her station. (hands don't reach)

![ScreenShot00022](https://user-images.githubusercontent.com/95461294/144785571-c0125b2e-d80c-495d-8cb7-9bcad8c91090.jpg)

Citadel: - 2 Keepers aren't positioned correctly. The one in the Citadel Tower closest to where Kahoku is located is not centered (the one at the console, not in the middle) and the one in C-SEC control center is positioned too high.
	    
![ScreenShot00004](https://user-images.githubusercontent.com/95461294/144548178-de681db1-0a1c-492d-ad1b-7783a2513461.jpg)

![ScreenShot00011](https://user-images.githubusercontent.com/95461294/144548221-e48bf340-5189-4beb-8680-3e8a29389b08.jpg)

- News report about "Citadel: Signal Tracking" will run if the quest is not completed and or even started. Its a bug from the original game.

Therum: - There is an invisible wall at the first set of fortified gates. (Not so much a wall as you can still shoot through it but more of a can't drive the mako over even though it looks flat enough to drive over).

![ScreenShot00001](https://user-images.githubusercontent.com/95461294/144548063-f880c705-86e1-4a43-9c8d-8e8cd19a7fbf.jpg)

Noveria: - There are guards that still have weird colored helmets. 
NOTE: It seems this is the only guard that has this helmet problem still.

![ScreenShot00012](https://user-images.githubusercontent.com/95461294/144548495-e123e89f-bff9-457b-8b75-30bc1e40fe45.jpg)

Feros: - Right after first contact with Fai Dan you are set upon by Geth. As you move your way up the first set of stairs, there is an individual who is missing his dialogue about not wanting to die right before getting blow up.

  ![image](https://user-images.githubusercontent.com/95461294/144773303-64f3c928-619f-4c3b-b52e-84cf720f3415.png)

![image](https://user-images.githubusercontent.com/95461294/144773652-204ae7d2-4bbb-490a-89b5-a51635211423.png)

(NOTE - I don't actually think this npc is in the LE version but the geth at the top still shoot at in that general direction.)

- The creepers(3 of them) on the first set of stairs in the Thorian chamber area do not activate.

![ScreenShot00009](https://user-images.githubusercontent.com/95461294/144548716-03be1186-d1cb-448d-bfe3-d16eba533dd7.jpg)

![ScreenShot00010](https://user-images.githubusercontent.com/95461294/144548752-e766dded-661d-4e39-861d-51cad58e08b2.jpg)

Bring Down the Sky: - The main base doesn't have a map marker.

- Also in the base there's a wall near the middle stairs on the right (the ones that lead down) that has a see through corner.

![ScreenShot00003](https://user-images.githubusercontent.com/95461294/144548622-2660900b-2604-4631-b3e9-12f01d1ee56d.jpg)

Planet Mavigon: - There is no map marker for the mummified Salarian (is it suppose to be unmarked?) also its referred to as 
                             mummified Salarian when its clearly a container. Maybe should be called "Coffin". idk. 

![ScreenShot00008](https://user-images.githubusercontent.com/95461294/144548566-e3cd88dc-78a4-4f62-83be-101f30582cf9.jpg)

Planet Agebinium: - There's a weird audio glitch where the wind cuts in and out. Mostly when traveling towards the mine.

**Comment by henbagle** [comment]
**Keeper Location Fixes:**
Citadel Tower Keeper (by Kahoku): File BIOA_STA70_02side_DSG.pcc
Last two instance UIndexes swapped in ArchetypeToInstanceMap in Export 7774 as they were incorrect. This fixed the terminal VFX. The keeper being off-center is still WIP as there's some weird collision stuff going on here.

C-Sec Academy Keeper: Set Export 1003 to Z value -21360.9 in BIOA_STA30_05a_DSG.pcc
![image](https://user-images.githubusercontent.com/8151477/144695199-91299946-61f2-4f19-a05a-d38c8a0cb434.png)

**Comment by ShredzAlot** [comment]
A few of the Keepers seem to have this problem with their terminal VFX not activating. If you save and reload then this fixes the problem. Once you leave however and return then it will happen again.

**Comment by henbagle** [comment]
Guy who gets killed by Geth right after meeting Fai Dan:
File: BIOA_WAR20_04a_DSG.pcc
He was getting killed by the Geth instantly even though the geth were supposed to "miss" him until after his line, something probably changed in the underlying native code breaking this scene.

Export 252 set to PlotProtected, ModifyPropertyPawn added to sequencing to make him killable again after he says his line.
![image](https://user-images.githubusercontent.com/8151477/144903917-c929dfac-e1a4-4585-9d2b-032c6bb745b0.png)

**Comment by henbagle** [comment]
Mavigon Salarian Artifact:
m_oAreaMap property added to Export 692 so the map note shows up on the planetary map after the artifact is scanned (not before). Not sure yet if we'll change the text, will update this comment if we do.

**Comment by henbagle** [comment]
The three Thorian Creepers on the stairs only activate if you go up to the top of the stairs before you destroy the first node, otherwise they never get activated at all. While an odd gameplay choice, it's not a bug, so I don't think we'll change it. Activating them would also potentially ruin the balance of the next fight.

**Comment by henbagle** [comment]
Fixed news report about Citadel: Signal Tracking. The elevator news report was set to play on completion of UNC: Rogue VI instead of Citadel: Signal Tracking. Someone must have confused their rogue AI missions.

Conditional 1138 updated via PlotManagerUpdate system to read the following

```
public function bool F1138(BioWorldInfo bioWorld, int Argument)
{
    local BioGlobalVariableTable gv;
    
    gv = bioWorld.GetGlobalVariables();
    return gv.GetBool(5440) == FALSE && gv.GetBool(5901) == TRUE;
}
```

**Comment by henbagle** [comment]
Ashley hands location fix:
File: BIOA_NOR10_11_DSG.pcc

Ashley (Export 1730) X position set to -6073.416
Ashley's Laptop (Export 2028) Z position set to -37398.242
Crate under laptop (Export 1514) Z position set to -37411.066


![image](https://user-images.githubusercontent.com/8151477/145459900-12d66fcb-4004-4b6e-9ffa-d6146ef29365.png)

**Comment by henbagle** [comment]
Pressley currently can't be moved for similar reasons as the keeper in the council chambers. As I'm preparing for the 1.2 release, I'm going to mark this issue as fixed, and open new issues for anything here that I haven't addressed yet.
