### ISSUE TITLE
The invisible Hanar on the Citadel

### ISSUE THREAD

**Issue by remix42** [henbagle/LE1CommunityPatch#110]
**Describe the bug**
Hanar the prophet disappeared after completing the quest. The first screenshot without LE1 Community Patch

**Screenshots & Saves**
https://i.ibb.co/HHF2tD9/nobug.jpg
https://i.ibb.co/PWRSJ9d/bug.jpg

**Comment by henbagle** [comment]
Would you be able to provide a savegame where the hanar is missing? Savegames can be found in Documents\Bioware\Mass Effect Legendary Edition\Save\ME1\{charactername}00. Just a single .pcsav file on the Citadel with the hanar missing would be enough.

**Comment by remix42** [comment]
[Aaei02_01.zip](https://github.com/henbagle/LE1CommunityPatch/files/7657226/Aaei02_01.zip)

**Comment by henbagle** [comment]
I have fixed this bug, and it will be included in our 1.2 update which should be out within the next week or so.
