### ISSUE TITLE
Noveria: Leaving Port Hanshan Journal Bug

### ISSUE THREAD

**Issue by ShredzAlot** [henbagle/LE1CommunityPatch#111]
There is a bug in the journal section that says I've been refused a garage pass even though I haven't even talked to the Admin. 

**To Reproduce**
Do the Noveria mission as you would normally do. Once you leave the first elevator the journal will update. Open the journal to confirm this. 

![image](https://user-images.githubusercontent.com/95461294/144955081-ca44912f-ed4e-4689-82b6-da927b5e2116.png)

![image](https://user-images.githubusercontent.com/95461294/144955485-3d5d80c5-009a-4666-afac-59835d36ac45.png)

NOTE: Might not be a bug but just a weird journal description for telling the player your not aloud to leave without permission. Will close the issue if this is the case.

**Comment by henbagle** [comment]
Fixed, TLK string 200004 added to to GlobalTlk, quest updated to use this string.

> You've discovered that Matriarch Benezia is on Noveria, but she's left the public port area. In order to proceed, you need to get a pass into the garage.
