### ISSUE TITLE
Navigator Pressley is not close enough to his console

### ISSUE THREAD

**Issue by henbagle** [henbagle/LE1CommunityPatch#116]
**Describe the bug**
When he is in his typing action station, Navigator Pressley's hands don't reach the console.

![image](https://user-images.githubusercontent.com/8151477/145466231-9a4428c7-781d-438f-bb65-7dbc3d5e4a53.png)

**Game file**
BIOA_NOR10_03_DSG.pcc. Currently unable to move him as his mesh would collide with the console mesh.

**Comment by henbagle** [comment]
Fixed by vegz for 1.7

**Comment by vegz** [comment]
Fixed by adding a path point into the file and making it so collision/snaptofloor is true for his actionstation.  

![image](https://github.com/henbagle/LE1CommunityPatch/assets/40906382/21d319dc-cfad-43d3-9391-288b86e6a7c9)
