### ISSUE TITLE
Fai Dan's corpse missing after his suicide

### ISSUE THREAD

**Issue by Herobrine24** [henbagle/LE1CommunityPatch#124]
**Describe the bug**
After clearing Zhu's Hope post-ExoGeni HQ, after the cutscene where Fai Dan shoots himself, his corpse is not present afterwards, only the blood puddle. Leaving the area and therefore unloading that section and returning to it will make his corpse appear.

(In the original, his corpse would stand up and be completely blacked out if you left the area and returned to it. Credit to [piefluff](https://www.twitch.tv/piefluff) for finding the OT bug.)

**To Reproduce**
1. Get Fai Dan to kill himself
2. Leave the area so that it unloads
3. Return to the area

**Expected behavior**
His corpse should be there post-cutscene like in the original.

**Screenshots & Saves**
![image](https://user-images.githubusercontent.com/73685731/155858592-3a6d73d6-bd71-468b-804a-34fb9fcf585d.png)
Only a puddle of blood is what remains of Fai Dan post-cutscene.
[Save_01.zip](https://github.com/henbagle/LE1CommunityPatch/files/8147469/Save_01.zip)

**Game file**
BIOA_WAR20_03c_DSG.pcc - Sets corpse
BIOA_WAR20_03_DSG.pcc - Remote Event Trigger for setting the corpse

**Comment by henbagle** [comment]
Fixed. Fai Dan pawn made active in the Fai_Dan_Dead sequence in BIOA_WAR20_03c_DSG.pcc when the remote event is called, before activating the action station.

![image](https://user-images.githubusercontent.com/8151477/172498751-e7e6bf17-a109-462e-a666-ed872dc04644.png)
