### ISSUE TITLE
Normandy: Ashley's precariously balanced terminal

### ISSUE THREAD

**Issue by sialivi** [henbagle/LE1CommunityPatch#126]
**Describe the bug**
Ashley's terminal is only half supported by the box it's placed on. The box also clips through the front edge of the desk.

**Expected behavior**
Move the box to the left so it supports the entire terminal, and move it back enough that it doesn't visibly clip through the front edge of the desk.

**Screenshots & Saves**
![Mass Effect Legendary Edition Screenshot 2022 03 15 - 17 46 57 38](https://user-images.githubusercontent.com/364734/158433798-6a5e7744-eccb-4b38-8c13-63eb54596901.png)

**Comment by henbagle** [comment]
Oops, looks like I didn't position that box properly when I was moving ashley's terminal to line up with her hands.

Fixed:
![image](https://user-images.githubusercontent.com/8151477/174506226-e3014c39-f0f7-479a-8c4d-a2547f763aaa.png)

Updated Location and Rotation of export 1514 in `BIOA_NOR10_11_DSG.pcc` to the following:
Location: (X=-6145.558, Y=13355.725, Z=-37411.066)
Rotation: (Pitch=16384, Yaw=262144, Roll=-114325)
Sorry in advance to all the other modders who now have to update compatibility for this file. I don't blame you if you skip out on patching this fix in.
