### ISSUE TITLE
Missing animations of scientists

### ISSUE THREAD

**Issue by praviilon** [henbagle/LE1CommunityPatch#139]
**Describe the bug**
On Chohe, inside the base with biotic fanatics (UNC: Besieged Base), the drugged scientists are supposed to wander around and move. This is their behaviour in OT ME1. In LE1 however they are stuck in the same place and are not moving at all. If any of them gets knocked out (by grenade or biotic attack) they get stuck and start A-posing once they get back up.

**Comment by mechcentric** [comment]
they stay put for me too

**Comment by vegz** [comment]
Fixed.

File: BIOA_UNC30_01_DSG

Export's: 1254, 1255, 1256, 1257

Bioware stripped the AI for the pawns for some reason so they are set as inactive, porting the ambient AI and linking it to their BioPawnChallengeType AIController property to match OT1 causes them to no longer be inactive.  Noticed the counter was broken as well and was able to fix that by making a new DUISetElementVisible. Bioware's autotrimming for sequence bocks, whenever they cooked the game ,broke this for some reason. 

![LE1CP](https://github.com/henbagle/LE1CommunityPatch/assets/40906382/d6f044b1-4b80-492f-bcd1-1110745c65b8)
