### ISSUE TITLE
nonuel mineral survey text error (OT oversight)

### ISSUE THREAD

**Issue by mechcentric** [henbagle/LE1CommunityPatch#143]
"Scans from orbit have revealed a large quantity of Titanium" text after surveying mineral on the planet (as of latest patch version on nexus)

**To Reproduce**
survey the titanium deposit on nonuel

**Expected behavior**
text should read like any other groundside titanium deposit survey

**Other Considerations**
maybe this quirk is charming but it is inaccurate

**Comment by ShredzAlot** [comment]
I second this. Also there is another planet with the same description but I can't remeber which one.

![Mass Effect 2022-05-25 6_09_05 PM](https://user-images.githubusercontent.com/95461294/170848511-01ddcfaa-e064-48b6-93f8-74a43d5affab.png)
Not Nonuel bottom one is.

![Mass Effect 2022-05-25 8_35_12 PM](https://user-images.githubusercontent.com/95461294/170848529-e7234c6e-ae7c-4dcf-bf57-c983139f047f.png)
This one is the one on Nonuel

**Comment by henbagle** [comment]
Fixed, GlobalTLK string 166554 updated to be like the other groundside surveys. This will fix all broken Titanium deposits in the game.

![image](https://user-images.githubusercontent.com/8151477/170886044-61292e6c-c2be-40a0-ac84-52e9b22da784.png)
