### ISSUE TITLE
Floating "Car" and Box Buried To Much

### ISSUE THREAD

**Issue by ShredzAlot** [henbagle/LE1CommunityPatch#145]
**Describe the bug**
The "car" on Nonuel is floating above the ground. And the crate is to far into the ground. That or the activation point is to far up. Both are at the same location.

**Screenshot**

![ScreenShot00040](https://user-images.githubusercontent.com/95461294/170848973-1bd66e2f-9073-4ada-806e-cb5a25e3db6a.jpg)

![Mass Effect 2022-05-25 8_27_09 PM](https://user-images.githubusercontent.com/95461294/170849030-6a0a04ec-2565-45ac-9036-f52cc825fae9.png)

**Comment by henbagle** [comment]
Fixed, Z values of export 961, 962, and 963 updated in BIOA_UNC42_00_DSG.pcc

![image](https://user-images.githubusercontent.com/8151477/170886706-f8d906c4-0e1b-426c-a193-a2a914173337.png)
