### ISSUE TITLE
Feros: "We can't take that chance" may doom the colony regardless of colonists saved

### ISSUE THREAD

**Issue by Loadingue** [henbagle/LE1CommunityPatch#154]
**Bug:**
Within the BioConv "war20_trigger_dlg", if Shepard confirms to squadmates that they should open fire on Thorian-affected Zhu's Hope colonists, their dialogue reply can fire 2 different transitions depending on the squadmate: Set_Thorian_Revealed_True or Set_Too_Many_Killed_True. The latter locks Zhu's Hope as having failed as a colony, regardless of the actual number of colonists killed afterwards. If you select this option and are with the wrong squadmate, the colony fails no matter how many you save. Kaidan, having first priority in replies, has Set_Too_Many_Killed_True. Garrus and Tali, respectively 4th and 5th priority, also have it. Ashley and Liara (2nd and 3rd) seem safe however, and one should be able to save the colony if they are present, as long as the other squadmate isn't Kaidan.

**Expected Fix:**
As "Set_Thorian_revealed_True" should have always been fired previously during the conversation with the ExoGeni VI, all transitions in the squadmates' replies can be removed

**Game Files:**
BIOA_WAR40_11_DSG_LOC_INT.pcc
BIOA_WAR20_05_DSG_LOC_INT.pcc
BIOA_WAR40V_00_DSG_LOC_INT.pcc
BIOA_WAR20_03c_DSG_LOC_INT.pcc
And all localizations

**Comment by henbagle** [comment]
Fixed. Transitions removed from dialogue entries 50-54 in war20_trigger_dlg in all files listed above, as well as all localized variants. Tested to work with a Kaidan/Garrus squad and a Ashley/Liara squad. Selecting "We can't take the chance" will allow your squadmates to fire at the colonists, but if you save all/enough of them, the outcome of the mission will still be "Colony Saved"

![image](https://user-images.githubusercontent.com/8151477/184382258-dcb57c9e-9865-4fe0-b1dd-38009f61ff33.png)
