### ISSUE TITLE
The music volume in the END presidium map doesn't play

### ISSUE THREAD

**Issue by vegz** [henbagle/LE1CommunityPatch#156]
**Describe the bug**
The music volume in BIOA_END00 labeled MusVol_END20_Presidium never plays in game unless a certain start position is touched by the player

**To Reproduce**
1. Put AT BIOA_END00 in console, the music plays after a few seconds 
2. Go though the relay on Ilos and the music doesn't play

*Expected behavior**
The music volume should be playing cause the music only doesn't play cause the Ilos area transition has a "broken" start location and doesn't hit the music volume trigger I assume.

**Other Considerations**
Probably not intended since the music volume is setup and actually plays. I think it's broken cause START_END20_00 is repeated in BIOA_END00 and is probably why it doesn't play. 

**Game file**
BIOA_END00

**Comment by henbagle** [comment]
Fixed. MusicVolumeEnable and CurrentMusicState set added to BIOA_END20_02_DSG.pcc to the same sequence that starts the Avina warnings. A MusicVolumeDisable has been added to the sequence that triggers the saren cutscene after the elevator ride in the same file, but I'm not sure if this is entirely needed. The music volume is kind of low, I will look into increasing the volume without affecting many more files.

![image](https://user-images.githubusercontent.com/8151477/201168920-9c035b6c-1b73-41c5-a234-26f8828ef6ce.png)
