### ISSUE TITLE
The transition from the Saren fight to the activation cutscene causes a loading popup to appear

### ISSUE THREAD

**Issue by vegz** [henbagle/LE1CommunityPatch#160]
**File:** BIOA_JUG00.pcc

**Needs fixed in localized file?** No

**Export ID/TLK Str Ref:** N/A

**Description of fix:**
As seen in the video here and from my testing, there is a quick streaming loading screen that appears during the transition from the battle to the cutscene. This is caused by them making a file visible that wasn't loaded in first. I was able to fix this by adding BIOA_JUG_80_X_Outrun to each triggerstream to be loaded no matter which streaming state  to match how the AA tower triggerstreams are.

[BIOA_JUG00.pcc](https://drive.google.com/file/d/1RGlXZRMluY1dEZddVjyfMYeQ9MCa0vo-/view?usp=sharing)
https://www.youtube.com/watch?v=iQc_CKsUCJo&t=596s

**Comment by Herobrine24** [comment]
you missed BioTriggerStream_6, its located within the Nuke arena, right infront of the unused elevator door that leads to an unfinished path leading to the AA tower. And from my testing, putting Outrun into Outbound is sufficient.

**Comment by henbagle** [comment]
Herobrine seems correct. `BIOA_JUG_80_X_Outrun` added to LoadChunkNames in streaming state Outbound in exports 323, 327, 328, 329, 330, 332, 341, 437 in BIOA_JUG00.pcc
