### ISSUE TITLE
Hallway mesh peaks through wall on Virmire

### ISSUE THREAD

**Issue by Herobrine24** [henbagle/LE1CommunityPatch#161]
**Describe the bug**
The wall mesh of the hallway that you go through before seeing the last AA tower that needs to be taken care of before the Normandy can land in Sarens base is visible through the wall on the outside and dissapears as you walk further away due to the next triggerstream not marking the hallway as visible

**To Reproduce**
Go to location

**Expected behavior**
No black strip on the wall next to the door.

**Other Considerations**
None

**Screenshots & Saves**
![image](https://user-images.githubusercontent.com/73685731/187487876-7aa0d547-98a2-4f52-b08b-582f856a38ce.png)
![image](https://user-images.githubusercontent.com/73685731/187487925-f527d391-5f10-4cfe-85bd-dfb362d3ffba.png)
[Char_03.zip](https://github.com/henbagle/LE1CommunityPatch/files/9454616/Char_03.zip)

**Game file**
BIOA_JUG70_12_LAY.pcc

**Comment by CATACHR1SM** [comment]
![image](https://user-images.githubusercontent.com/27882475/214669375-e01dd257-d010-4d34-b215-f940815716f6.png)
Luckily, no mesh modding needed, just add scale3d to export 145 and set x y and z to .995 to resolve.

![image](https://user-images.githubusercontent.com/27882475/214670124-6a7a96ce-a801-42e5-b3d0-017123cab5c3.png)
