### ISSUE TITLE
Hidden away Normandy is visible on Virmire

### ISSUE THREAD

**Issue by Herobrine24** [henbagle/LE1CommunityPatch#162]
**Describe the bug**
When looking back out onto the ocean from the geth barricade thats only made up of shields, you can clearly see the Normandy hiding in plain sight 

**To Reproduce**
Look back from the geth barricade made out of shields on Virmire

**Expected behavior**
Normandy shouldn't be visible.

**Other Considerations**
None

**Screenshots & Saves**
![image](https://user-images.githubusercontent.com/73685731/187494158-afe81d71-7bad-40e9-8946-31182854bc74.png)
[Save_04.zip](https://github.com/henbagle/LE1CommunityPatch/files/9454890/Save_04.zip)

**Game file**
BIOA_JUG20_00_DSG

**Comment by henbagle** [comment]
Fixed in BIOA_JUG20_00_DSG. Normandy set to hidden on level load, unless hover interp should be playing.

![image](https://user-images.githubusercontent.com/8151477/199115872-3f6f1e94-a573-4841-822f-40015d91e48a.png)
