### ISSUE TITLE
Destiny Ascension in complete darkness during flyby

### ISSUE THREAD

**Issue by Herobrine24** [henbagle/LE1CommunityPatch#165]
**Describe the bug**
The destiny ascension's hull is completely black except for the light emitting materials on it when it does its flyby in front of the Wards after you help Garrus and Dr. Michel. https://www.youtube.com/watch?v=rGgbsxwFRYI

**To Reproduce**
1. Help Dr. Michel and Garrus
2. Step out into the wards and observe

**Expected behavior**
https://www.youtube.com/watch?v=_6bwWs7cIIo

**Other Considerations**
None

**Screenshots & Saves**
[Alden00_07.zip](https://github.com/henbagle/LE1CommunityPatch/files/9478622/Alden00_07.zip)

**Game file**
Possibly BIOA_STA60_01destiny.pcc

**Comment by CATACHR1SM** [comment]
Fixed

![Acention lighitng fix](https://user-images.githubusercontent.com/27882475/200725333-5c8520fb-e316-48d9-a469-8c9b255891e3.jpg)
[BIOA_STA60_01destiny_DSG.zip](https://github.com/henbagle/LE1CommunityPatch/files/9966873/BIOA_STA60_01destiny_DSG.zip)

**Comment by CATACHR1SM** [comment]
I set lighting channel on destiny ascension to dynamic
