### ISSUE TITLE
Feros Skyway-Zhu's Hope Elevator is incorrectly lit

### ISSUE THREAD

**Issue by Herobrine24** [henbagle/LE1CommunityPatch#166]
**Describe the bug**
Due to the lighting changes on Feros, the Zhu's Hope-Skyway elevator is lit brighter than its surroundings.

**To Reproduce**
Observe/Use Elevator after dealing with the geth in the tower

**Expected behavior**
Possible look with BIOA_WAR20_00_ART streamed out
![image](https://user-images.githubusercontent.com/73685731/188173043-4f7f1a7d-eae8-4e59-9a5c-65af6bfe8c37.png)
![image](https://user-images.githubusercontent.com/73685731/188173130-7b219c80-5b1e-46ba-8c34-26337d4d463b.png)

**Other Considerations**
Its possible that BioWare left the elevator lit brighter in order to make the interior more visible to players but it could also be an oversight.

**Screenshots & Saves**
OT Skyway
![image](https://user-images.githubusercontent.com/73685731/188171580-f6591d01-e2ac-40de-afaa-074556b26169.png)
LE Skyway
![image](https://user-images.githubusercontent.com/73685731/188171595-c33f5c06-a333-466a-9347-588494d11848.png)
OT Zhu's Hope
![image](https://user-images.githubusercontent.com/73685731/188171919-e625d49a-1ada-426b-93df-e8c3abb82663.png)
LE Zhu's Hope
![image](https://user-images.githubusercontent.com/73685731/188171971-8cf969e0-b445-4b43-b4f5-992439103e4d.png)

**Game file**
Possibly BIOA_WAR20_00*

**Comment by CATACHR1SM** [comment]
https://youtu.be/hVa-m6ZUEeE

Fixed: 
[elevator fix.zip](https://github.com/henbagle/LE1CommunityPatch/files/9993603/elevator.fix.zip)
