### ISSUE TITLE
The Saren Nihlus Cutscene doesn't trigger after talking to the scientists on Eden Prime

### ISSUE THREAD

**Issue by vegz** [henbagle/LE1CommunityPatch#167]
**Describe the bug**
Looking at the comments for OT1, there is a comment stating that the cutscene should trigger after talking to the scientists or at the triggervolume. There seems to not be a trigger for the cutscene after the dialogue ends.

**To Reproduce**
Talk to the scientists on Eden Prime after the husks, no cutscene will trigger. 

**Expected behavior**
The cutscene should trigger after talking to them or hitting the trigger volume.

**Screenshots & Saves**
![EdenPrime](https://user-images.githubusercontent.com/40906382/188290503-37b776b4-d692-427a-8584-c3a38f45ea93.png)

**Game file**
BIOA_PRO10_07_DSG

**Comment by henbagle** [comment]
I don't consider sequence comments as accurate depictions of developer intent when it comes to recognizing bugs. This could be cut content, or could have been changed on purpose for any reason and the comment was just not updated. This is also a pretty sizeable change to story flow in the prologue, so I don't think we should do anything about this. If there is some actual sequencing somewhere that isn't hooked up properly that would cause the cutscene to trigger, that would be a different story.
