### ISSUE TITLE
Another Large Collection of Planet/Surfaces/Journal Misspellings, Weird Descriptions, Etc

### ISSUE THREAD

**Issue by ShredzAlot** [henbagle/LE1CommunityPatch#177]
### **Planets**

![Mass Effect-Alsages Planet](https://user-images.githubusercontent.com/95461294/204179275-151ff811-fdbe-4fd1-852d-1f9b5e44da6f.jpg)
- Remove Small (and its comma) and capitalize distant or reword the sentence as "Alsages is a small distant terrestrial"

![Mass Effect-Altaaya Planet](https://user-images.githubusercontent.com/95461294/204179278-54970a1a-ca23-4467-afb1-2b8ef69338f3.jpg)
- Should be 11,190 km

![Mass Effect-Antirumgon Planet](https://user-images.githubusercontent.com/95461294/204179280-b9eda0dd-f62f-4714-81eb-49dbfbc62416.jpg)
- Missing the G

![Mass Effect-Chofen Planet](https://user-images.githubusercontent.com/95461294/204179281-9f714e3f-b711-4ee1-84f2-38f5320861ba.jpg)
- Should be 21,481 km

![Mass Effect-Chohe Planet](https://user-images.githubusercontent.com/95461294/204179283-145737ca-7373-41c9-9996-56071e0de814.jpg)
- Should probably be changed to "the planet" instead but this ones optional (Yellow)
- to "the" extremes (Red)

![Mass Effect-Citadel](https://user-images.githubusercontent.com/95461294/204179307-eec7a5d0-1aa0-4614-9f26-1e60be21c413.jpg)
- One space two many

![Mass Effect-Farcrothu Planet](https://user-images.githubusercontent.com/95461294/204179309-9f461533-1ba8-4847-9e2a-ada33c3379b5.jpg)
- Remove gas

![Mass Effect-Junthor Planet](https://user-images.githubusercontent.com/95461294/204179310-83e5616c-e7c7-499f-8aaa-11219c4d903d.jpg)
- "gravity" needs to be capitalized

![Mass Effect-Luna Planet](https://user-images.githubusercontent.com/95461294/204179312-cd26bfea-767c-4380-8d8d-04a8059a4ea2.jpg)
- One space two many

![Mass Effect-Nepheron Planet](https://user-images.githubusercontent.com/95461294/204179313-8c8d60a1-793c-4f4e-bd19-0c27a2a7bec7.jpg)
- One space two many

![Mass Effect-Parag Planet](https://user-images.githubusercontent.com/95461294/204179315-623fee8e-6fd5-49d7-a972-e5ee1f2ff401.jpg)
- Missing the ":"

![Mass Effect-Porolan Planet](https://user-images.githubusercontent.com/95461294/204179317-ee454eb3-e4a8-4780-8fbd-3fc3beec41bb.jpg)
- Not actually sure about this one

![Mass Effect-Therumlon Planet](https://user-images.githubusercontent.com/95461294/204179343-b9b3d155-495c-41e1-8ba5-df66bba08297.jpg)
- Should be "surprisingly" 

![Mass Effect-Trebin Planet](https://user-images.githubusercontent.com/95461294/204179344-c630cbf8-e6e0-4eee-818e-e6e7f0134a81.jpg)
- One space two many

![Mass Effect-Wermani Planet](https://user-images.githubusercontent.com/95461294/204179345-31a73557-a69c-4a1c-a43b-55091c1614aa.jpg)
- Should be 71,541 km

![Mass Effect-Wuo Planet](https://user-images.githubusercontent.com/95461294/204179346-ece8209d-5ab3-4f7a-a85d-5647bfb90f0a.jpg)
- Pretty sure it should be Gorgon not Wuo

### **Planet Surfaces**

_Antibaar_
![Mass Effect 2022-05-25 9_26_57 PM](https://user-images.githubusercontent.com/95461294/204181204-188a61ee-eaa4-4600-aad9-30685b84362d.png)
![Mass Effect 2022-05-25 9_27_18 PM](https://user-images.githubusercontent.com/95461294/204181209-dc0d61da-83b5-4368-8f62-79c2458fcf86.png)
- Is Shepard searching inside the ruins or outside them. This never made sense to me and I don't know if its just stupid writing

_Metgos_
![Mass Effect 2022-10-16 6_04_21 PM](https://user-images.githubusercontent.com/95461294/204181298-2dc99d10-164b-4b67-84f2-8c4c6766e5fb.png)
![Mass Effect 2022-10-16 6_04_39 PM](https://user-images.githubusercontent.com/95461294/204181302-6cbd4f90-3426-4291-b563-459948826c6b.png)
- Should be called Turian Wreckage not corpse 

_Nempos_
![Mass Effect 2022-11-22 1_46_40 PM](https://user-images.githubusercontent.com/95461294/204181352-fb81aceb-0b1c-4b5a-8fc8-be0521ef6ece.png)
![Mass Effect 2022-11-22 1_46_52 PM](https://user-images.githubusercontent.com/95461294/204181358-b3ba33dc-9d84-4a4b-9b61-10ea3f149542.png)
- Should probably say something to the extent of "This safebox has a League of One medallion in it. Whether it was buried here by a miner that found it while digging is beyond me." Or something like that. 

_Tuntau_
![Mass Effect 2022-11-23 2_51_38 PM](https://user-images.githubusercontent.com/95461294/204182858-026e4051-299d-46cd-b52b-2ff73848178c.png)
![Mass Effect 2022-11-23 2_51_53 PM](https://user-images.githubusercontent.com/95461294/204182863-41ffa424-1f39-40e5-9076-914c40a94772.png)
- It's really up to you which one should be changed.

UPDATE:
_Solcrum_
![Mass Effect 2022-05-25 10_01_03 PM](https://user-images.githubusercontent.com/95461294/204617984-5eae5866-1bf5-4922-9211-3ad1ad030671.png)
- I didn't know this place was a dig site. There's nothing around to indicate it ever was. Maybe just changing the last sentence to "Wherever it was found is unclear." Location is in that elevated crater.

### **Journal**

![Mass Effect 2022-05-20 11_33_34 AM](https://user-images.githubusercontent.com/95461294/204183024-be379c24-3b17-45cd-8aec-a512ba2d968b.jpg)
- Should probably be "agents" (actual quotations in the sentence). I don't think this is a typo but it just looked funny

 ![Mass Effect 2022-05-25 7_00_41 PM](https://user-images.githubusercontent.com/95461294/204183204-fa7e3e92-d3b2-405b-83c2-0ed88316b621.jpg)
- Needs an "a" in between

![Mass Effect 2022-09-14 3_18_11 PM](https://user-images.githubusercontent.com/95461294/204183257-de222cb0-9579-45c7-b80d-a88a0c06b4f5.jpg)
- Remove one of the systems

![Mass Effect 2022-11-22 1_05_53 PM](https://user-images.githubusercontent.com/95461294/204183335-dc11ce76-7e7f-4e9e-898a-b7a398136749.jpg)
- "colony" needs to be capitalized. plus actually replacing "Colony" with the word "Facility". 

![Mass Effect 2022-11-23 1_11_14 PM](https://user-images.githubusercontent.com/95461294/204183613-9d62f1a5-ca39-4d34-91f3-e7e6d143c6f2.png)
- Should be reworded to say you need to take out 2 more bases cause thats how many more you need to take out after the first one is destroyed.

 ![Mass Effect 2022-11-22 2_07_23 PM](https://user-images.githubusercontent.com/95461294/204184081-b0679847-a6aa-4e33-a3be-e68e9d8116bc.png)
- Needs a mission completion description added. Maybe something like "Listening Post Alpha has been saved from further rachni attacks".

**UPDATE**

### **CONVO**
In one (if not the last) conversation you can have with Wrex.
![Mass Effect 2022-05-25 10_31_45 PM](https://user-images.githubusercontent.com/95461294/204618816-fe8e6d58-5f3c-4079-9b6d-8cbc96e473a3.png)
Not actually sure if this is intentional or even if it really matters but if not then it should be "what about the fight?" not "what bout the fight?".

**Comment by henbagle** [comment]
The clear misspellings and grammar mistakes have been fixed and will be included in the next update, including all the number and spacing issues, and the Wrex conversation thing.

The Listening Post Alpha journal appears to be a bug, as there is actually mission completion text in the quest that does not appear to be firing. I will take a look and add a solution to issue #105. 

The planet surface issues are known. I will take a look but so many of them have weird wording or map issues that can be easily ignored. I've previously opted to leave a lot of them as they are unless they are particularly egregious. Fixing the text is not simple because it requires being translated into every language the game supports, it's not like a grammar or spelling mistake that is limited to English.
