### ISSUE TITLE
Some Building and Object Problems

### ISSUE THREAD

**Issue by ShredzAlot** [henbagle/LE1CommunityPatch#185]
**Amaranthine Base**
![ScreenShot00020](https://user-images.githubusercontent.com/95461294/204921004-4d73e0a3-41d1-4b4d-af20-485e3301f2fb.jpg)
Building is sunken into the ground to much.

**Planet Altahe**
![Mass Effect 2022-11-22 2_15_44 PM](https://user-images.githubusercontent.com/95461294/204921565-1f643865-44a3-4f45-8397-e11bc62243e4.png)
![Mass Effect 2022-11-22 2_15_21 PM](https://user-images.githubusercontent.com/95461294/204921575-8c7cec04-b9bf-412b-81d9-c4681e1a2886.png)
Main base and the rachni mounds are hovering to much. Hard to tell with these angles but they are.

**Nodacrux Main Base**
![ScreenShot00035](https://user-images.githubusercontent.com/95461294/204922037-71b53a8e-9f10-44a8-a607-4ef19333f870.jpg)
Thorian nest at the entrance is sunken to much into the ground.

**Citadel Wards District**
![Mass Effect 2022-08-03 2_42_38 PM](https://user-images.githubusercontent.com/95461294/204922324-4e66c610-43b2-4e38-9cab-76f1d174553a.png)
Anyone whose come from the wards access section to the main wards area, you've probably heard a crate just go bang. I believe the crate is positioned at a weird angle and/or is getting pushed out of placement due to object bounds. Or something like that I'm no tech guy.

**Comment by henbagle** [comment]
Z values in Export 751, 1114, 3758, and 3760 updated in BIOA_UNC24_01_DSG.pcc for floating stuff on Altahe. 

Updated many z values in BIOA_UNC31_01_DSG.pcc to fix Amaranthine sunken base. The ground is slightly sloped so it isn't perfect but it's much better. 
![image](https://user-images.githubusercontent.com/8151477/211683958-923872ee-0fb8-4a8a-a573-7d3d642c32da.png)

**Comment by henbagle** [comment]
Nodacrux Thorian Pod: Z value and drawscale updated on export 3082 in BIOA_UNC80_02_DSG.pcc

![image](https://user-images.githubusercontent.com/8151477/213529979-2c2d6387-fe19-4cef-96b4-957c6e4eb329.png)

**Comment by henbagle** [comment]
Investigating the crate that goes bang. It's difficult to trigger so I am having a hard time fixing it. I believe it is BioInert_2 in BIOA_UNC60_03A_DSG.pcc but I am unsure.

**Comment by ShredzAlot** [comment]
Here's a video of the crate noise and a pic of the crate out of place. Its suppose to be "standing" up.

https://user-images.githubusercontent.com/95461294/217326631-923fccd5-6824-457f-a7ac-42d94009d939.mp4

![Mass Effect 2023-02-07 11_48_13 AM](https://user-images.githubusercontent.com/95461294/217326883-83139854-4d8e-4063-8483-0a0f67e2aefa.png)
