### ISSUE TITLE
Mercenary corpses inside base on Ontarom still have pink visors

### ISSUE THREAD

**Issue by Ukhupa** [henbagle/LE1CommunityPatch#190]
**Describe the bug**
The three mercenary corpses inside the base on Ontarom that you visit during UNC: Dead Scientists still have pink visors

**To Reproduce**
Load up a save where Ontarom is available for travel, land, and head into the base with LE1 Community Patch v1.3 installed.

**Expected behavior**
Visors should be opaque black and the white parts should be green like the rest of the helmet. The two corpses _outside_  the base display the correct colors. 

![20230115152410_1](https://user-images.githubusercontent.com/122753775/212568594-02109adf-f789-48e3-a768-2eaa000f6a97.jpg)
![20230115152445_1](https://user-images.githubusercontent.com/122753775/212568608-6632eb38-5e7f-43ee-a0ec-b63f605e835e.jpg)
![20230115152544_1](https://user-images.githubusercontent.com/122753775/212568614-f2886a5b-23c6-4d0d-99ae-7260f3500bb0.jpg)

**Comment by henbagle** [comment]
This was an incompatibility with version 1.0 of MELLO that has now been resolved with version 1.1. Closing the issue.
