### ISSUE TITLE
On Nonuel, 2 thresher maws and a mineral survey are placed outside the bound lines

### ISSUE THREAD

**Issue by henbagle** [henbagle/LE1CommunityPatch#20]
**Describe the bug**
On Nonuel, 2 thresher maws and a mineral survey are placed outside the bound lines, making tackling them very tricky without being reset

**Screenshots & Saves**
[Jane00_22 - Sithdoom.zip](https://github.com/henbagle/LE1CommunityPatch/files/6835589/Jane00_22.-.Sithdoom.zip)

![Mass Effect Legendary Edition Screenshot 2021 05 18 - 14 49 10 42 - Sithdoom](https://user-images.githubusercontent.com/8151477/126054084-4f0c33f3-9262-4022-a28e-c0802ecb59af.png)

**Comment by 55tumbl** [comment]
I have a fix fo this.
