### ISSUE TITLE
Error installing mod: HUDFixes.m3m: DLL not found

### ISSUE THREAD

**Issue by EvgenijIvanov** [henbagle/LE1CommunityPatch#202]
Hi!
Steps to reproduce:
1) Download an install ME3Tweaks Mod Manager
2) Download  LE1 Community Patch
3) Import patch to mod manager
4) Install game MELE from Origin
5) Try apply mod
6) Error
![image](https://user-images.githubusercontent.com/23220588/226217262-166da595-f802-4e02-9ebf-7147955c278b.png)

**Comment by henbagle** [comment]
This is an issue with [ME3Tweaks Mod Manager](https://github.com/ME3Tweaks/ME3TweaksModManager). Please report this issue on their issue tracker, or on their discord. You will need to include a link to a log, which can be found in the tools menu of the mod manager. This is not an issue with the LE1 Community Patch.
