### ISSUE TITLE
Nihlus Facial Animations don't work in comm room during prologue

### ISSUE THREAD

**Issue by jogzy123** [henbagle/LE1CommunityPatch#203]
**Describe the bug**
Nihlus's lips (or whatever the turian equivalent is) do not move during the conversation with Shepard in the Comm room at the start of the prologue. This appears to be specific to this scene, as his facial animations seem to work fine for all other scenes in the prologue. This appears to be a problem with the patch itself, not the vanilla game, as disabling the patch via the mod manager fixes the animation bug.

**To Reproduce**
Follow the prologue until entering the comm room and initiate the conversation with Nihlus. His facial animation will be bugged. Disabling the patch fixes the issue. I have tried this twice now and it reproduced successfully.

**Expected behavior**
Nihlus should have lip movement when he speaks during the scene.

**Other Considerations**
Given that this seems obvious I am surprised that this bug has not been noticed. I am wondering if this is specific to my game but I do not see how this could be possible as I have no other mods installed whatsoever except the community patch.

**Comment by henbagle** [comment]
It's fine for it to be open in both places, thanks for the detailed report.

**Comment by henbagle** [comment]
This has been fixed locally and will be included in the next update. Thanks to Vegz for fixing it 😄 

File: BIOA_NOR10_04_DS1.pcc

Outlinks removed from Export 4511 to the two Preload Conversation inlinks on the Nihlus conversation. For some unknown reason, preloading the conversations was causing this issue. Starting the conversations without preloading has no ill effects.
