### ISSUE TITLE
Calantha Blake Dialogue Audio cuts out early on Zhu's Hope

### ISSUE THREAD

**Issue by jogzy123** [henbagle/LE1CommunityPatch#206]
**Describe the bug**
Two of the lines of dialogue spoken by Calantha Blake, an NPC found in the medical room on Zhu's hope cut out slightly before they finish, eliminating a few words. This does not seem to be a case of the subtitles not matching the dialogue, since she cuts out midway through voicing the words. This is a very minor bug to say the least, as not only is she is a minor NPC with barely any dialogue, but she is also delirious so her not speaking properly doesn't even break immersion all that much. But I noticed it so I might as well point it out.

**To Reproduce**
After repelling the Geth attack and speaking with Fai Dan, Speak to Calantha Blake, who is lying on the bed in the medical room of Zhu's hope alongside her husband Hollis. Speak directly to her, and not Hollis, as I believe that speaking to him first might stop the short cutscene with Calantha from playing. (I'm not sure about this, but I triggered the bug by speaking to Calantha first, and I dont recall ever triggering this cutscene on any previous playthrough). This consistently reproduces.

**Expected behavior**
Calantha Blake should finish speaking her dialogue lines without being cut off early.

**Other Considerations**
It's possible that the audio is just incomplete from Bioware, in which case there is nothing to be done. This is a minor NPC after all, so incomplete audio might have easily just been missed in this case, but I have no way of knowing as I have no idea how to access the audio file. I'm no mod maker myself. 

I had finished all of the objectives for the following, but had not spoken to the required NPC's to initiate or complete the quests. I highly doubt this is relevant whatsoever, but I'm putting them here just in case: 

Assignment: [Feros: Geth in the Tunnels]
Assignment: [Feros: Power Cells]
Assignment: [Feros: Varren Meat]
Assignment: [Feros: Water Restoration]

**Screenshots & Saves**
Save File Included

[Jane00_15.zip](https://github.com/henbagle/LE1CommunityPatch/files/11163387/Jane00_15.zip)

**Comment by AudemusN7** [comment]
I looked into this and this appears to be part of the wider conversation bugs that result in certain (seemingly random) lines being cut off that are dependent on if the player is male or female. In this case, playing as FemShep will result in two of Calantha's lines cutting off early.

This may be able to use the same solution used in Pinnacle Station, depending on if the issue is with the start or the end of the line. I have a similar bug in LE1DP with a restored Tartakovsky line that can't be fixed the same way because it's a delay with the ConvLine itself firing.

**Comment by henbagle** [comment]
Fixed the same way that #127 was fixed. Only an issue when playing as femshep.

_M FXA copied over to _F FXA on FXA_13215 and FXA_13217 in war20_calanthablake_Owner_F.

BIOA_WAR20_03b_DSG_LOC_INT.pcc and BIOA_WAR20_03d_DSG_LOC_INT.pcc

**Comment by henbagle** [comment]
Does not appear to be an issue on other localizations.
