### ISSUE TITLE
Quarantine guard on Noveria has a line with a missing actor tag so the gesture gets assigned to the player

### ISSUE THREAD

**Issue by vegz** [henbagle/LE1CommunityPatch#207]
**File:** BIOA_ICE060_06_DSG_LOC_INT.pcc

**Needs fixed in localized file?** Yes

**Export ID/TLK Str Ref:** N/A

**Description of fix:**
Bioware forgot to give the gestures an actor tag for the "I have ventralis' permission to go in there" so the player will go from standing to holding an invisible gun. Its an easy fix and just requires to add the owner actor tag to the line.

**BEFORE**
![bug](https://user-images.githubusercontent.com/40906382/233818833-7f2c01c1-36ce-4f61-9456-d305ca6fe2de.PNG)

**AFTER**

![fixed](https://user-images.githubusercontent.com/40906382/233818845-d75dde5a-c842-46f1-94fb-31d2cec7cd4c.PNG)

**Comment by henbagle** [comment]
Fix implemented in all localizations 👍
