### ISSUE TITLE
Calyn's lines uses an incorrect bool check

### ISSUE THREAD

**Issue by vegz** [henbagle/LE1CommunityPatch#209]
**File:** BIOA_STA20_10D_DSG_LOC_XXX.pcc

**Needs fixed in localized file?** Yes

**Export ID/TLK Str Ref:** Entry node 1 and 4 in sta20_elcor_ambassador_dlg

**Description of fix:**
The bools are the old version of "player is spectre" plot and wasn't updated for the new transitions when they rewrote the plotline. Changing the bool from 2479 to 3916 allows both of the lines to play correctly, matching the other npcs that comment on your spectre status.

BEFORE:
![image](https://github.com/henbagle/LE1CommunityPatch/assets/40906382/f5fa8e81-730c-4711-9d90-c1e5055687fb)
![image](https://github.com/henbagle/LE1CommunityPatch/assets/40906382/1d4dc902-1173-42ec-9a74-37fbf7d5c2f3)

AFTER:
![1](https://github.com/henbagle/LE1CommunityPatch/assets/40906382/31435097-0119-4397-a30c-ff69581f34f9)
![2](https://github.com/henbagle/LE1CommunityPatch/assets/40906382/55d3d8ec-5d94-46b8-b3d4-749d51bfb252)

**Comment by henbagle** [comment]
Fixed for all localizations and will be included in 1.4.1.
