### ISSUE TITLE
Ashley and Kaidan line on Virmire use Wrong ActorNameOverride StrRef

### ISSUE THREAD

**Issue by vegz** [henbagle/LE1CommunityPatch#225]
**File:** BIOA_JUG40_01_DSG.pcc

**Needs fixed in localized file?** NO

**Export ID/TLK Str Ref:** 157 and 161

**Description of fix:**
The FaceOnlyVO sequence actions are using Captain Kirrahe as the ActorNameOverride for some reason. Changing the str override from 151260 to 149286 on Export 157 and from 151260 to 149287 on export 161 fixes the subtitles.

**Comment by henbagle** [comment]
Fixed locally and will be included in the next update.
