### ISSUE TITLE
Dr Saleon conversation repeats without Garrus

### ISSUE THREAD

**Issue by AudemusN7** [henbagle/LE1CommunityPatch#226]
**File:** BIOA_FRE34_00_DSG.pcc

**Needs fixed in localized file?** Is this a LOC_INT file, but the fix is not specific to english?
No

**Export ID/TLK Str Ref:**
#12595 - Garrus_PlotEncounter Sequence

**Description of fix:**
If the player kills Dr Saleon without Garrus present, then bool 5361 is set to true. However, the sequence only checks if bool 5350 is true, which is only set if Saleon is killed with Garrus present. If the player kills Saleon without Garrus, lets the door to his room close, and then opens it again, the conversation will trigger once more (this time with an invisible/mute Saleon since he's dead).

The simplest fix for this is to simply add an additional plot check for bool 5361 to the sequence:
![LegendaryExplorer_nf3uK3Sda5](https://github.com/henbagle/LE1CommunityPatch/assets/44449267/942624f8-6247-4da7-930a-8c3e0fc81f69)

**Comment by henbagle** [comment]
Fixed locally and will be included in next update! 👍
