### ISSUE TITLE
The Karpov Pistol (and possibly the Brawler) is missing a material

### ISSUE THREAD

**Issue by costantino2000** [henbagle/LE1CommunityPatch#228]
The Karpov Pistol from Rosenkov Materials is missing the (5a) material, this makes the gun look blue instead of white:
![Screenshot (775)](https://github.com/henbagle/LE1CommunityPatch/assets/86307814/b9b0d64c-dd9f-4d3e-a36f-049cfcc8b240)

There is already a mod that fixes the issue (it also shows how the pistol is supposed to look), but it's not fixed in the community patch: https://www.nexusmods.com/masseffectlegendaryedition/mods/1591

Also, while checking for this bug I saw that the Brawler has the same texture, but on the wiki it looks different, maybe that pistol requires a fix too.

**Comment by henbagle** [comment]
Fixed. [Restored Karpov Pistol](https://www.nexusmods.com/masseffectlegendaryedition/mods/1591?tab=description) mod integrated with permission from Mistyvail. Will take a look at the Brawler.
