### ISSUE TITLE
JUG80_POD01 Material is missing properties in LE

### ISSUE THREAD

**Issue by AudemusN7** [henbagle/LE1CommunityPatch#230]
**File:** 
All files that use this material are affected:
- BIOA_ICE60_14_LAY
- BIOA_JUG40_02_LAY
- BIOA_JUG40_04_LAY
- BIOA_JUG40_05_LAY
- BIOA_JUG40_08_LAY
- BIOA_JUG70_02_LAY
- BIOA_JUG70_03_LAY
- BIOA_JUG70_05_LAY
- BIOA_JUG70_06_LAY
- BIOA_JUG70_11_LAY
- BIOA_JUG70_14_LAY
- BIOA_JUG70_16_LAY
- BIOA_JUG80_05_LAY
- BIOA_JUG80_06_LAY
- BIOA_JUG80_07_LAY
- BIOA_JUG80_08_LAY
- BIOA_JUG80_09_LAY

Additionally, Pinnacle Station pulls this asset into **BIOA_PRC2_CCTHAI**

**Needs fixed in localized file?** Is this a LOC_INT file, but the fix is not specific to english?
No

**Description of fix:**
For some reason, JUG80_POD01 appears to have missing properties in Legendary Edition. The emissive is gone, as well as the normal map which was present in OT. To fix this I have substituted with a cloned version of Geth_Terminal_01_material, which has all the material properties needed:
- Cubemap
- Normal Map
- Uses GEN_Metal_01 as the PhysMaterial
- Emissive

On the texture side:
- I pulled the spec out of the alpha channel of JUG80_POD01_DIFF, which is now a new texture (JUG80_POD01_SPEC)
- The original diffuse is now DXT1 with no alpha (JUG80_POD01_DIFF_NEW)
- I added a new emissive texture (JUG80_POD01_Emis) 
- I pulled the normal map from OT and AI upscaled it to match LE quality (JUG80_01_NORM)

The new material can be found **[here](https://cdn.discordapp.com/attachments/865303859201835048/1186283895382081546/JUG80_POD01_-_New_Material.pcc?ex=6592aff8&is=65803af8&hm=f0da3d534b35a9b21a89197811cee663dcd3603543ee7b4af5817f7b77abfb56&)**

Every mesh that references the original material needs to be relinked to this one in the files listed above.

OT1
![](https://cdn.discordapp.com/attachments/865303859201835048/1186030816963334214/image.png)

LE1 Vanilla
![](https://cdn.discordapp.com/attachments/865303859201835048/1186031193876078814/PNGLE1ScreenShot00021.png)

FIXED
![](https://cdn.discordapp.com/attachments/865303859201835048/1186030850979152013/PNGLE1ScreenShot00020.png)

**Comment by henbagle** [comment]
Material has been cloned and relinked into all listed files
