### ISSUE TITLE
Normandy Softlock during Virmire Bomb Site

### ISSUE THREAD

**Issue by UtilityPawn** [henbagle/LE1CommunityPatch#237]
similar to #163 on LE1CP but if you speak to squadmates while Joker says his line the game softlocks and the Normandy doesn't arrive. 

https://github.com/henbagle/LE1CommunityPatch/assets/154812945/93810fab-92b5-4b34-b67e-4ee95d7b4bad

**Comment by UtilityPawn** [comment]
the log at the time of doing it https://me3tweaks.com/modmanager/logservice/logviewer?logid=ca34bfb2cf138e983217ed83fd51b289

**Comment by henbagle** [comment]
Fixed in the same manner as #163 

File: BIOA_JUG80_00_PLC.pcc

![image](https://github.com/henbagle/LE1CommunityPatch/assets/8151477/a88b8dfc-32f9-4bc9-8a50-9deef7c5edac)
