### ISSUE TITLE
Shepard & companions make a dash move before starting their walk animation (all locations)

### ISSUE THREAD

**Issue by AliceQuinzel** [henbagle/LE1CommunityPatch#239]
**Describe the bug**
When walking is enabled, everytime the characters (player & npcs) start moving, for a split second their running animation is activated, then abruptly switches to walking.

**To Reproduce**
Just hit the walk button and walk anywhere.

**Expected behavior**
Proper walk animation.

**Other Considerations**
This was not intended and the original ME 1 didn't have this issue.

**Comment by henbagle** [comment]
Closing - Duplicate issue to #98
