### ISSUE TITLE
Ashley refers to FemShep as 'Sir' in conversation after Eden Prime

### ISSUE THREAD

**Issue by henbagle** [henbagle/LE1CommunityPatch#25]
**Describe the bug**
When I was talking to Ashely as a FemShep after Eden Prime she referred to me as a Sir when talking about how I survived.

**Other Considerations**
This bug will probably not be fixed, as it is not possible to edit audio in LE1 at this time. This also seems intended by BioWare. Female shepard can speak to both Ashley and Kaidan after Eden Prime, but male shep can only speak to Ashley.

**Comment by SirCxyrtyx** [comment]
Not a bug, since “sir” can be gender neutral in military settings.
