### ISSUE TITLE
Faulty Conditional Setup on story progression comments from Dr. Chakwas

### ISSUE THREAD

**Issue by Herobrine24** [henbagle/LE1CommunityPatch#256]
**Describe the bug**
Dr. Chakwas has 3 comments pertaining to your progress through the main story that never trigger due to the Conditional parameter being inverted.

**To Reproduce**
Talk to Dr. Chakwas post-Eden Prime, after becoming a Spectre and after acquiring Liara.

**Expected behaviour**
Dr. Chakwas says her 3 lines:
"I'm glad to see you're feeling better, Commander."
"The asari are remarkable, aren't they? Can you believe Liara is twice my age?"
"The crew's lives are in your hands, Shepard. Try to take good care of them."

**Other Considerations**
This was most likely an accident rather than a deliberate change, as the lines are fully functional.

**Game file**
BIOA_NOR10_07_DSG_LOC_*.pcc

**Comment by henbagle** [comment]
Conditional Parameter set to 0 on E4, E6, and E8 of nor10_doctor_dlg.

Fixed in BIOA_NOR10_07_DSG_LOC_*.pcc as well as BIOA_NOR10_06wake_DSG_LOC_*.pcc
