### ISSUE TITLE
Upgrade 2DA merges to M3DA format

### ISSUE THREAD

**Issue by henbagle** [henbagle/LE1CommunityPatch#267]
Move the mod to MM9 and upgrade our 2DA table merges to the new M3DA format.

Depending on framework release timing, we may need to release a 1.7.1 when MM9 is out so our 2DA tables don't break when the rest of the scene moves to the new manager version.

**Comment by Mgamerz** [comment]
Mod Manager 9 beta begins on Friday June 28. You will want to ship your M3DA then but keep it on 8.2 until full release.

**Comment by henbagle** [comment]
Issues #50 and #155 have been converted over to M3DA format as of 1.7.1. The merge mod has been left alone so users on MM 8.2 can still install the mod properly.

Once MM9 is released, we will convert #224 to M3DA, the only remaining issue using AutoLoad to merge into a 2DA. We will also remove the 2DA merge mod, and update to cmmver 9.

**Comment by TheOne320** [comment]
What is the status on this? MM9 was released. Can I still use 1.7.1 or should I wait for an update? Thanks for all your hard work.

**Comment by henbagle** [comment]
Compatibility for MM8.2 has now been removed, all 2DA tables are updated via 2DA merge format as of LE1CP 1.7.2
