### ISSUE TITLE
Missing Label for the FOV Slider in Settings

### ISSUE THREAD

**Issue by s29817** [henbagle/LE1CommunityPatch#270]
**Describe the bug**
When using Polish text, the description of the FOV Slider in the Settings is missing. It shows up as $3402320.  It appears correctly as Field of View in English.
This was working correctly as of version 1.6, I believe. I'm not sure if any other text was lost in translations.

**To Reproduce**
Choose Polish in the Game Launcher. Go to Extras -> Options -> Mod controlled game settings.

**Expected behavior**
The label of the slider should be saying FOV or "Pole widzenia".

**Screenshots & Saves**
![obraz](https://github.com/user-attachments/assets/4c3bc11e-594a-4a17-bc40-6f92c24c77f4)

**Comment by s29817** [comment]
One additional thing I noticed when switching to English is that labels in Gameplay Settings do not render correctly.

**Comment by henbagle** [comment]
Fixed, a couple strings somehow got dropped out of 1.7 for polish language.

Will be included in 1.7.2
