### ISSUE TITLE
Throw/Lift/Warp can only hit multiple enemies when targeted at terrain or objects

### ISSUE THREAD

**Issue by Bradxkillyou** [henbagle/LE1CommunityPatch#39]
**Describe the bug**
Throw, Lift, and Warp cannot hit multiple enemies when an enemy is directly targeted with the targeting reticle, regardless of the listed radius of the ability. These abilities will correctly hit multiple targets in a radius around the targeting reticle when it is aimed at terrain or an object.

**To Reproduce**
Attempt to hit multiple targets in a tight group with any of the aforementioned abilities. Targeting the floor in front of them will always yield the intended effect of the ability, while targeting one of them will only ever hit that enemy.

**Expected behavior**
Throw, Lift, and Warp should hit all enemies in the listed radius around the point of impact when an enemy is directly targeted with the ability, unless there is an obstruction between the point of impact and the enemy, such as a wall.

**Other Considerations**
Shepard and their allies are already fully capable of using these biotics to their full potential, so long as they always target the floor or other objects. This fix would make these abilities easier to use to their intended effect, and prevent the frustration of not being able to target the floor or a wall when enemies are in close-quarters or tightly clustered around the desired point of impact. It's clear from talent descriptions that these powers are meant to impact in a radius in order to hit multiple enemies.

**Screenshots & Saves**
Lift is targeted at the floor...
![liftfloor2](https://user-images.githubusercontent.com/87795309/126590659-9c19b899-7219-435a-ae1c-903f11808fd8.png)

... and both targets are lifted.
![twolifted](https://user-images.githubusercontent.com/87795309/126590749-91b26bb0-6e4b-4f81-bae6-55ad123f32d1.png)

An enemy in the center of a group is targeted... 
![liftfailtarget](https://user-images.githubusercontent.com/87795309/126590839-805da143-e5dc-41e1-8529-0d53ff7ace45.png)

... and only that enemy is lifted.
![liftliftliftfail](https://user-images.githubusercontent.com/87795309/126590869-39d578f5-13eb-465b-9023-bd3b9b62895a.png)

Warp is targeted at the floor... 
![floorwarp](https://user-images.githubusercontent.com/87795309/126590912-026a6802-f5dd-4143-8e45-42a3197c9541.png)

... and multiple targets are affected - note the damage vulnerability values have both been increased to 1.84, and how all 3 enemies are emitting a blue aura after being affected by a biotic power.
![reducedDRmulti](https://user-images.githubusercontent.com/87795309/126590981-5fab7e21-4d47-40a5-bfca-35703a26c9d6.png)
![reducedDRmulti2](https://user-images.githubusercontent.com/87795309/126590989-6a2a6264-be34-4022-a74b-0b39098a3f84.png)

An enemy in a group is targeted with Warp...
![warptarget](https://user-images.githubusercontent.com/87795309/126591010-25a58919-0ece-4e1d-8321-cb7b594da9e4.png)

... and the surrounding enemies are left unaffected - the second enemy still has their default damage vulnerability of 1. You can also see that the targeted enemy has lost a tiny bit of health from Warp's DoT and is affected by the blue aura, where the second enemy has full health and no aura.
![warptargetfail](https://user-images.githubusercontent.com/87795309/126591082-c51ef34b-50c7-4649-b33c-e6336ad501d1.png)
![warptargetfail2](https://user-images.githubusercontent.com/87795309/126591091-f3dd89df-2c1f-44db-93e2-ebeb45728be6.png)

I forgot to screenshot throw hitting multiple enemies when targeted at the floor, but here's what happens when targeted at an enemy.
![throwtarget](https://user-images.githubusercontent.com/87795309/126591203-dd951787-89af-42d7-9630-4fb820383fa2.png)
![throwfail](https://user-images.githubusercontent.com/87795309/126591217-fda42687-fbec-4da1-acb1-003e015e65da.png)

**Game file**
I'd guess it has something to do with the scripts in SFXGameContent_Powers - perhaps the BioPowerScriptDesign class, which I think the scripts for all powers inherit from. Tech powers do not suffer from this limitation and always hit all enemies within the powers radius, so I imagine looking at how the radius/targeting of tech powers works might yield some insight on how to fix this.

EDIT: Found two functions in the BioPowerManager in SFXGame, CheckLOStoActor and CheckLOStoLocation - not sure where they're actually defined but I imagine these have something to do with it.

**Comment by Bradxkillyou** [comment]
I found a fix for this - turns out the fact that biotics cannot penetrate cover is part of the problem here. By changing the bBlockedByCover variable in the TalentEffectLevels 2DA (Engine.pcc, under BIOG_2DA_Talents_X) from 1 to 0 on these 3 biotics, they now correctly hit all enemies within a radius of the targeted enemy. I _believe_ the source of the issue here is how line of sight is calculated from the point of impact. When casting Throw/Lift/Warp targeted at an enemy, I think the impact location is created _inside_ of that enemy - any potential line of sight to another enemy is then blocked by the targeted enemies' character model/hitbox, and so the game regards the other enemies as "behind cover" because it cannot draw an unbroken line to them. This leads me to believe that the only other ways of solving this problem would be to alter native functions, or to offset the impact location of these powers somehow, such that the point of impact is not inside of the targeted enemy (which may be possible by fiddling with power scripts).

I guess I'll need some feedback from the community here since this fix does have slight gameplay implications - giving these biotics the ability to properly hit all enemies in their intended radius when targeting an enemy would also mean that these biotics can now penetrate cover, in the same way that Tech powers and Singularity already do. Personally, I don't think this is a big issue because in any situation where this change would allow you to hit an enemy behind cover, there is usually already a location on the floor, ceiling, or a wall that could be targeted for the same effect. In my experience, whether or not an enemy is behind cover is rarely of consequence when attempting to target that enemy with these 3 biotics, and so I think the pros of this fix greatly outweigh the cons.

**Comment by henbagle** [comment]
Wow, great find!

**Comment by 55tumbl** [comment]
I wouldn't include this in the community patch, tbh.

- The behaviour is indeed not consistent, but it's not absolutely obvious to me in which way it is bugged. All this seems to happen in native functions, so we can't tell for sure. But could be e.g. if the power hits a target they consider it's good enough and simply do not look for another one, but if the power hits the world they look for a target nearby, with the bug being they do not stop the loop when one is found. 

- These powers being blocked by obstacles is definitely intended.

- Making these powers hit through obstacles is a significant buff to biotic powers, which are already OP af. Sure, there may often be a way to target floor or walls, etc. But 1) not always, 2) I guess most people do not know this, 3) targeting walls/floors is a lot more difficult than targeting autolocked enemies, especially when not pausing the game. Plenty of times my powers sent at the environment to try to go around obstacles ended up way further cause I didn't get the angle exactly right.

- Could be checked if it's the same behaviour in the original game, but I think there's a pretty established meta, with people recommending to use Lift vs. bigger targets, and Singularity vs. groups of smaller grunts, etc. Such a change would make the powers a lot less distinct.

- The corresponding powers in the next games affect only a single target by default (unlike Singularity), unless specific radius evolutions are available and taken. Whether they decided that having all powers affecting everything in radius is a bit much while working on the power balance in ME1 (but after writing the descriptions), or between ME1 and ME2 is anyone's guess.

**Comment by henbagle** [comment]
I agree with all of 55tumbl's points. It's very difficult to say for certain that this is a bug, and it could radically affect gameplay.

This is something that could very easily become it's own mod, and I would love to see it get released.
