### ISSUE TITLE
Can't enter M29 Grizzly on Noveria

### ISSUE THREAD

**Issue by Blackbird88** [henbagle/LE1CommunityPatch#65]
**Describe the bug**
In the original ME1 you were able to hack and [enter M29 Grizzly in the Noveria garage](https://www.reddit.com/r/masseffect/comments/iyw0i1/little_known_detail_you_can_hack_the_m29_grizzly/). On my last playthrough of LE1 this wasn't possible.

**To Reproduce**
On Noveria when you get attacked by the geth in the garage try to hack the M29 Grizzly. The marker will be missing.

**Expected behavior**
You should be able to hack it and enter it like in the original game.

**Other Considerations**
It is possible it got broken by BioWare's Mako changes.

**Comment by vegz** [comment]
The entire sequence was deleted from the file so we couldn't restore the grizzly unless we port ME1 files over. They definitely did it on purpose and isn't a bug.

**Comment by henbagle** [comment]
New information has come to light that this feature was cut by BioWare because it was too buggy and they didn't have time to fix it before release. Because of this, we will be trying to fix it and include it with our next update.

**Comment by henbagle** [comment]
Audemus has restored this and it will be included. 

Files updated: BIOA_ICE20_09_DSG.pcc, BIOA_ICE20_09_LAY.pcc. The lay file is to remove collision on the static rover.

**Comment by henbagle** [comment]
Feature made optional in MCM through sequencing in BIOA_ICE20_09_DSG.pcc. Bool 8101, true means feature disabled, false means feature enabled (default).

**Comment by henbagle** [comment]
New issue with this: As soon as your shields are depleted, the rover gets 1 hit killed, health does not deplete at all.

**Comment by henbagle** [comment]
Fixed, m_fDamageVulnerability on Export 12393, the VehicleBehavior for the rover was set to 9999, presumably making it extremely vulnerable. I believe this should be a percentage, but I'm not totally sure. Setting it to 0.5 felt like a reasonably balanced option.
