### ISSUE TITLE
Missing Tracer when meeting Lizbeth Baynhem

### ISSUE THREAD

**Issue by Herobrine24** [henbagle/LE1CommunityPatch#68]
**Describe the bug**
The tracer effect when Lizbeth shoots the squad is missing.

**To Reproduce**
Encounter Lizbeth on Feros

**Expected behavior**
https://youtu.be/ANXdlfoqK3I?t=488

**Screenshots & Saves**
https://user-images.githubusercontent.com/73685731/133921621-41d92bf6-ae0a-40f1-8758-34a7d10092fc.mp4

**Game file**
BIOA_WAR50_03_*

**Comment by henbagle** [comment]
File: BIOA_WAR50_03_CIN.pcc

Fixed by changing the DrawScale property from 0.4 to 0.5 on the tracer (Emitter_0, export 126). I have no idea why this fixes it.

https://user-images.githubusercontent.com/8151477/135701928-831cdf7e-13a2-4ad8-9107-0b683fcc807e.mp4
