### ISSUE TITLE
Incorrectly lit Aft Docking Clamp on Citadel

### ISSUE THREAD

**Issue by Herobrine24** [henbagle/LE1CommunityPatch#71]
**Describe the bug**
The aft docking clamp holding the Normandy on the Citadel seems to be incorrectly lit.

**Expected behavior**
![image](https://user-images.githubusercontent.com/73685731/133925606-dabdfeee-0ed9-49d2-a453-4966d561c06d.png)
![image](https://user-images.githubusercontent.com/73685731/133925629-ff9164e7-d632-4f50-91eb-dae712578bb7.png)

**Screenshots & Saves**
![image](https://user-images.githubusercontent.com/73685731/133925572-86738f30-5aef-4fe3-95bd-52de8fb58f5c.png)

**Game file**
BIOA_STA30_02

**Comment by henbagle** [comment]
Fixed. LightingChannels Unnamed_4 and Unnamed_5 set to true, Dynamic set to false on exports 393 and 394 in BIOA_STA30_02_LAY.pcc. This makes the lighting channels the same as the other Normandy docking arm.

![image](https://user-images.githubusercontent.com/8151477/144694601-9e814c63-e34f-4a81-bea9-3327545f8b2e.png)
