### ISSUE TITLE
Eddie Lang Typo

### ISSUE THREAD

**Issue by Herobrine24** [henbagle/LE1CommunityPatch#72]
**Describe the bug**
The subtitles say "Securtiy" at the end.

**To Reproduce**
Interact with Eddie Lang for the first time.

**Expected behavior**
The subtitles should say "Security" at the end.

**Screenshots & Saves**
![image](https://user-images.githubusercontent.com/73685731/133925797-e5964c82-ff4f-4cea-b87c-42074a5b8492.png)

**Game file**
BIOA_STA60_08_*

**Comment by henbagle** [comment]
Fixed via GAME1_TLK_MERGE
