### ISSUE TITLE
Relay Monument animation has a slight pause

### ISSUE THREAD

**Issue by Herobrine24** [henbagle/LE1CommunityPatch#73]
**Describe the bug**
During the endgame, the Relay Monument Core starts spinning. This animation however visibly pauses before it loops again.

**To Reproduce**
"At BIOA_END00"

**Expected behavior**
Uninterrupted spinning like with all other Relays.

**Screenshots & Saves**
https://user-images.githubusercontent.com/73685731/133926795-5a4db22f-f925-415d-9eab-645f54d79798.mp4

**Game file**
BIOA_END20_02_*

**Comment by henbagle** [comment]
**File:** BIOA_END20_04_PLC.pcc

Final rotation key removed from the END20_OuterRing and END20_innerring tracks in the state_opened AnimSequence, export 11. NumFrames and CompressedTrackOffsets updated to account for this.
