### ISSUE TITLE
Typo when sacrificing the Council

### ISSUE THREAD

**Issue by Herobrine24** [henbagle/LE1CommunityPatch#74]
**Describe the bug**
Subtitles say "overwhlemed".

**To Reproduce**
Sacrifice the Council.

**Expected behavior**
Subtitles should say "overwhelmed".

**Screenshots & Saves**
![image](https://user-images.githubusercontent.com/73685731/133927622-fc7f5f40-1d33-4051-b10a-5863d8e0e621.png)
[John00_03.zip](https://github.com/henbagle/LE1CommunityPatch/files/7192088/John00_03.zip)

**Game file**
BIOA_END_70*

**Comment by henbagle** [comment]
Fixed via GAME1_TLK_MERGE
