### ISSUE TITLE
Game softlocks on Ilos if you do the trench run on foot

### ISSUE THREAD

**Issue by AudemusN7** [henbagle/LE1CommunityPatch#78]
**Describe the bug**
If for whatever reason you decide to do the trench run on foot, once you reach the Conduit run it is impossible to get to it in time.

**To Reproduce**
At any point during the trench run on Ilos, get out of the Mako and leave it behind far away enough that you can't reach it after the cutscene that plays when you come into sight of the Conduit.

**Expected behavior**
Some have claimed that in the original, there was a barrier that prevented you from progressing past a certain point on foot that isn't present in LE1. Even so, I don't think a barrier would completely solve the problem. The game would need to spawn the Mako next to you if you left it behind in order to completely fix the problem.

**Other Considerations**
This might sound like a ridiculous edge case, but apparently a lot of people have done this. I have no idea why you would spend 20 minutes walking down a path obviously designed for vehicular traversal, but hey - a soft lock is a soft lock.

**Comment by henbagle** [comment]
New sequencing added to BIOA_LOS50_06_DSG.pcc to teleport the Mako behind the player after the Citadel Attack cutscene, if the player is on foot. PathNode export 7778 added to represent the location the Mako will teleport to.

![image](https://user-images.githubusercontent.com/8151477/135527783-e7f777ac-e2ab-4195-ac96-03fb3a1c19e7.png)
