### ISSUE TITLE
Citadel councillor names are inconsistent throughout the Trilogy.

### ISSUE THREAD

**Issue by henbagle** [henbagle/LE1CommunityPatch#8]
**Describe the bug**
In Mass Effect 1, the councillors were referred to as "Asari Councillor" and "Turian Councillor". In LE1, they have been changed to "Tevos" and "Sparatus"

**Proposed behavior**
Change the councillor's subtitle names to "Councillor Tevos", "Councillor Sparatus", etc.

This fix is open for community discussion and input as to whether it is worth including.

**Comment by Mgamerz** [comment]
This seems like a fairly low impact change. I would not be opposed to a small change like this since the experience doesn't really change if you see their names or not.

**Comment by henbagle** [comment]
Fixed. TLK string overrides added to GlobalTlk file.
![image](https://user-images.githubusercontent.com/8151477/129104228-19872fef-31d7-4942-b317-ac9b77d18b1d.png)
