### ISSUE TITLE
Softlock in Endgame Citadel Geth Ship section

### ISSUE THREAD

**Issue by Herobrine24** [henbagle/LE1CommunityPatch#81]
**Describe the bug**
The interactable props behind the turrets that activate them can be destroyed, causing a softlock if all three are destroyed.

**To Reproduce**
"At BIOA_END00 Start_END80_07"
Shoot the interactable props behind the turrets until they cannot be interacted with.

**Expected behavior**
These props should be indestructible.

**Other Considerations**
It is an extreme edge case and I haven't seen anyone actually destroy those intentionally or accidentally, and since thats a combat area you could reload a previous save/autosave before that section.

**Game file**
BIOA_END80_07_*

**Comment by henbagle** [comment]
m_bPlotProtected and m_bPlotProtectedOverride both set to True for exports 105, 106, and 107 in BIOA_END80_07_DSG.pcc
